// ─────────────────────────────────────────────────────────────────────────────
// TransUnion × Conquer AI — Sample Fraud Alert Data
// Represents the incoming signal stream the triage agent processes
// ─────────────────────────────────────────────────────────────────────────────

const SAMPLE_ALERTS = [
  {
    id: "ALT-2026-0041",
    timestamp: new Date(Date.now() - 4 * 60000).toISOString(),
    source: "FDE-Primary v3.1",
    alertType: "card_not_present",
    priority: "HIGH",
    status: "pending",
    customer: { id: "CUS-887234", segment: "Premium", country: "GB" },
    signal: {
      transaction_amount: 4750.00,
      currency: "GBP",
      merchant: "TechStore International",
      merchant_country: "NG",
      card_holder_country: "GB",
      transaction_channel: "Online",
      device_fingerprint: "NEW_DEVICE",
      ip_address_country: "NG",
      ip_risk_score: 0.91,
      velocity_24h: 9,
      velocity_7d: 11,
      avg_transaction_size: 145.50,
      time_since_last_transaction_mins: 12,
      3ds_authenticated: false,
      billing_shipping_match: false,
    }
  },
  {
    id: "ALT-2026-0042",
    timestamp: new Date(Date.now() - 11 * 60000).toISOString(),
    source: "FDE-Primary v3.1",
    alertType: "account_takeover",
    priority: "CRITICAL",
    status: "pending",
    customer: { id: "CUS-223419", segment: "Standard", country: "US" },
    signal: {
      event_type: "Password reset + email change",
      login_ip_country: "RU",
      registered_country: "US",
      device_fingerprint: "NEW_DEVICE",
      ip_risk_score: 0.95,
      logins_failed_24h: 7,
      password_changed: true,
      email_changed: true,
      mfa_bypassed: true,
      time_to_transaction_after_change_mins: 4,
      transaction_amount: 2100.00,
      currency: "USD",
    }
  },
  {
    id: "ALT-2026-0043",
    timestamp: new Date(Date.now() - 18 * 60000).toISOString(),
    source: "FDE-Secondary v2.4",
    alertType: "synthetic_identity",
    priority: "MEDIUM",
    status: "pending",
    customer: { id: "CUS-991122", segment: "New", country: "US" },
    signal: {
      ssn_issued_state: "WY",
      applicant_address_state: "NY",
      credit_file_age_days: 11,
      number_of_inquiries_30d: 8,
      thin_file: true,
      ssn_first_use_age: "adult",
      name_address_mismatch: true,
      phone_number_age_days: 9,
      credit_requested: 15000,
      income_stated: 95000,
      employer_verification_failed: true,
    }
  },
  {
    id: "ALT-2026-0044",
    timestamp: new Date(Date.now() - 27 * 60000).toISOString(),
    source: "FDE-Primary v3.1",
    alertType: "card_not_present",
    priority: "LOW",
    status: "pending",
    customer: { id: "CUS-445567", segment: "Premium", country: "CA" },
    signal: {
      transaction_amount: 89.99,
      currency: "CAD",
      merchant: "Netflix Canada",
      merchant_country: "CA",
      card_holder_country: "CA",
      transaction_channel: "Online",
      device_fingerprint: "KNOWN_DEVICE",
      ip_address_country: "CA",
      ip_risk_score: 0.08,
      velocity_24h: 2,
      velocity_7d: 8,
      avg_transaction_size: 92.00,
      3ds_authenticated: true,
      billing_shipping_match: true,
    }
  },
  {
    id: "ALT-2026-0045",
    timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
    source: "Identity Engine v1.9",
    alertType: "identity_verification_fail",
    priority: "HIGH",
    status: "pending",
    customer: { id: "CUS-778843", segment: "New", country: "GB" },
    signal: {
      document_type: "Passport",
      document_country: "GB",
      document_expiry: "2027-08-14",
      liveness_check: "FAIL",
      face_match_score: 0.41,
      document_authenticity_score: 0.62,
      address_verification: "PARTIAL",
      pep_sanction_hit: false,
      device_fingerprint: "NEW_DEVICE",
      application_type: "Current Account",
      requested_overdraft: 2500,
    }
  },
  {
    id: "ALT-2026-0046",
    timestamp: new Date(Date.now() - 52 * 60000).toISOString(),
    source: "FDE-Primary v3.1",
    alertType: "first_party_fraud",
    priority: "MEDIUM",
    status: "pending",
    customer: { id: "CUS-332211", segment: "Standard", country: "US" },
    signal: {
      dispute_count_12m: 4,
      chargeback_count_12m: 3,
      dispute_win_rate: 0.92,
      avg_dispute_amount: 340,
      most_recent_dispute_days_ago: 18,
      transaction_amount: 520.00,
      merchant: "Electronics Depot",
      pattern_match: "high_dispute_velocity",
      account_age_days: 712,
      previous_fraud_flag: false,
    }
  },
  {
    id: "ALT-2026-0047",
    timestamp: new Date(Date.now() - 68 * 60000).toISOString(),
    source: "FDE-Secondary v2.4",
    alertType: "card_not_present",
    priority: "LOW",
    status: "pending",
    customer: { id: "CUS-112358", segment: "Premium", country: "US" },
    signal: {
      transaction_amount: 1250.00,
      currency: "USD",
      merchant: "Apple Store",
      merchant_country: "US",
      card_holder_country: "US",
      transaction_channel: "In-App",
      device_fingerprint: "KNOWN_DEVICE",
      ip_address_country: "US",
      ip_risk_score: 0.05,
      velocity_24h: 1,
      avg_transaction_size: 980.00,
      3ds_authenticated: true,
      billing_shipping_match: true,
    }
  },
  {
    id: "ALT-2026-0048",
    timestamp: new Date(Date.now() - 89 * 60000).toISOString(),
    source: "FDE-Primary v3.1",
    alertType: "account_takeover",
    priority: "HIGH",
    status: "pending",
    customer: { id: "CUS-567890", segment: "Business", country: "GB" },
    signal: {
      event_type: "Unusual login location",
      login_ip_country: "CN",
      registered_country: "GB",
      device_fingerprint: "NEW_DEVICE",
      ip_risk_score: 0.78,
      logins_failed_24h: 3,
      password_changed: false,
      email_changed: false,
      mfa_bypassed: false,
      time_since_last_login_days: 4,
      transaction_amount: 8900.00,
      currency: "GBP",
    }
  }
];

const ALERT_TYPE_LABELS = {
  card_not_present: "Card Not Present",
  account_takeover: "Account Takeover",
  synthetic_identity: "Synthetic Identity",
  identity_verification_fail: "Identity Verification Fail",
  first_party_fraud: "First Party Fraud",
};

const PRIORITY_CONFIG = {
  CRITICAL: { color: "#F13C47", bg: "rgba(241,60,71,0.12)", label: "CRITICAL" },
  HIGH:     { color: "#FFA030", bg: "rgba(255,160,48,0.12)", label: "HIGH" },
  MEDIUM:   { color: "#00A8CB", bg: "rgba(0,168,203,0.12)", label: "MEDIUM" },
  LOW:      { color: "#38BB94", bg: "rgba(56,187,148,0.12)", label: "LOW" },
};
